In [30]:
#Import numpy
import numpy as np

In [31]:
# random value array of 2 X 3
random_array = np.random.random((2,3))
print(random_array)

[[0.09428396 0.45123974 0.74053609]
 [0.46291636 0.96434551 0.54068261]]


In [32]:
#Addition of Two numpy arrays
array_a = np.array([10,20,30,40,50])
array_b = np.arange(5)

array_c = array_a + array_b
print("Array c = Array a + Array b:\n",array_c,"\n")

Array c = Array a + Array b:
 [10 21 32 43 54] 



In [33]:
#Subtraction of Two numpy arrays
array_a = np.array([10,20,30,40,50])
array_b = np.arange(5)

array_d = array_a - array_b
print("Array d = Array a - Array b:\n",array_d,"\n")

Array d = Array a - Array b:
 [10 19 28 37 46] 



In [34]:
# Multiplication of Two numpy arrays
array_a = np.array([10,20,30,40,50])
array_b = np.arange(5)

array_e = array_a * array_b
print("Array e = Array a * Array b:\n",array_e,"\n")

Array e = Array a * Array b:
 [  0  20  60 120 200] 



In [35]:
# Matrix multiplication

A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
                [3,4]])
# Method 1:
print("Method-1 matrix multiplication:\n",A@B,"\n")

#Method 2:
print("Method-2 matrix multiplication:\n",A.dot(B))

Method-1 matrix multiplication:
 [[5 4]
 [3 4]] 

Method-2 matrix multiplication:
 [[5 4]
 [3 4]]


In [36]:
print(array_b**2)
print(array_a>30)

[ 0  1  4  9 16]
[False False False  True  True]
