In [1]:
#Import numpy
import numpy as np

# `Numpy Array`

### To create Numpy array:

In [2]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a= np.arange(15).reshape((5,3))
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [4]:
a = np.arange(0,15).reshape((3,5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
a = np.arange(10,15).reshape((1,5))
print(a)

[[10 11 12 13 14]]


In [6]:
b = np.array([3.14,3.15])
print(b)

[3.14 3.15]


### Numpy attributes: 

In [7]:
print(a.dtype)
print(b.dtype)

int64
float64


In [8]:
print(a.shape)
print(b.size)

(1, 5)
2


In [9]:
print(a.ndim)
print(b.ndim)

2
1


In [10]:
print(a.itemsize)
print(b.itemsize)

8
8


In [11]:
print(a.size)
print(b.size)

5
2


In [12]:
print(type(a))
print(type(a))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
