In [81]:
#Import numpy 
import numpy as np

In [82]:
#Two Dimensional Array
two_dimensional_array = np.array([[1,2,3.14],
                                  [5.6,7,8]])
print("Datatype:",two_dimensional_array.dtype)
print("Shape:",two_dimensional_array.shape)
print("Array:\n",two_dimensional_array)

Datatype: float64
Shape: (2, 3)
Array:
 [[1.   2.   3.14]
 [5.6  7.   8.  ]]


In [83]:
#Numpy Complex value Array
complex_array = np.array([[1,2],[3,4]],dtype=complex)
print("Data type:",complex_array.dtype)
print("Shape:",complex_array.shape)
print("Array: \n",complex_array)

Data type: complex128
Shape: (2, 2)
Array: 
 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [84]:
#Numpy zero array of int type but default is float
numpy_zeros_array = np.zeros((2,3),dtype=int)
print("Data type :",numpy_zeros_array.dtype)
print("Array: \n",numpy_zero_array)

print()

#Numpy zero array of float type 
numpy_zeros_array = np.zeros((3,2))
print("Data type :",numpy_zeros_array.dtype)
print("Array: \n",numpy_zero_array)

Data type : int64
Array: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

Data type : float64
Array: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [85]:
# numpy ones array of int type
numpy_ones_array = np.ones((2,3),dtype=int)
print("Data type:",numpy_ones_array.dtype)
print("Array:\n",numpy_ones_array)

print()

# Numpy ones array of float type
numpy_ones_array = np.ones((3,2),dtype=float)
print("Data type:",numpy_ones_array.dtype)
print("Array:\n",numpy_ones_array)

Data type: int64
Array:
 [[1 1 1]
 [1 1 1]]

Data type: float64
Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [86]:
#Array based on no. of elements
array = np.linspace(1,5,5)
print("Data type:",array.dtype)
print("Shape:",array.shape)
print("Array:",array)

Data type: float64
Shape: (5,)
Array: [1. 2. 3. 4. 5.]


In [87]:
# Array based on range and/or of specific dimension
array = np.arange(5)
print("Data type:",array.dtype)
print("Shape:",array.shape)
print("Array:\n",array)

print()

# Array based on given range and dimension
array = np.arange(0,10).reshape((2,5))
print("Data type:",array.dtype)
print("Shape:",array.shape)
print("Array:\n",array)

Data type: int64
Shape: (5,)
Array:
 [0 1 2 3 4]

Data type: int64
Shape: (2, 5)
Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
